# Generated by Django 5.1.7 on 2025-03-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='null', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
