# Generated by Django 5.1.7 on 2025-03-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='waiting_data',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
