# Generated by Django 5.1.7 on 2025-04-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='answered_quiz_questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='quiz_score',
            field=models.IntegerField(default=0),
        ),
    ]
