# Generated by Django 5.1.7 on 2025-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_quiz_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
